# Generated by Django 3.1 on 2020-09-07 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='matches',
            table=None,
        ),
        migrations.AlterModelTable(
            name='players',
            table=None,
        ),
        migrations.AlterModelTable(
            name='rankings',
            table=None,
        ),
    ]
