# Generated by Django 3.1 on 2020-09-07 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score_app', '0002_auto_20200907_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='matchdate',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='matches',
            name='matchday',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='matches',
            name='matchname',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='players',
            name='playername',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='players',
            name='pointsinvested',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='players',
            name='datejoined',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
