# Generated by Django 3.1 on 2020-09-13 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('score_app', '0004_wins'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalpoints', models.IntegerField()),
                ('distinctplayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score_app.players')),
            ],
        ),
    ]
